eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


microservices:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/api/v1/payment/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/api/v1/user/

test:
  value: HELLO-WORLD-JAVA

logging:
  file:
    name: /Users/dhanesh/ecom-app-logs/ecom-app.log
