# server:
#   port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

microservices:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/api/v1/payment/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/api/v1/user/

test:
  value: HELLO-WORLD-JAVA-1

logging:
  file:
    name: /Users/dhanesh/ecom-app-logs/ecom-app.log
  # pattern:
  #   level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  health:
      circuitbreakers:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    health:
#      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    # distribution:
    #   percentiles-histogram:
    #     http:
    #       server:
    #         requests: true
  endpoint:
    # web:
    #   exposure:
    #     include: prometheus
    health:
      show-details: always
